#!/bin/bash

#get battery level and state
batValue=$(acpi -b | awk '{print $4}' | sed "s/[^0-9]//g")
batState=$(acpi -b | awk '{print $3}' | sed "s/[^a-Z]//g")

#if battery is charging
if [ $batState == "Charging" ]; then
	#use bold blue colour
	returnString="\e[1;36m"
else
	#of battery is discharging
	if [ $batState == "Discharging" ]; then
		#if less than 1/4 remain
		if [ $batValue -lt 25 ]; then
			#if it's less than 10%
			if [ $batValue -lt 10 ]; then
				#use flashing high-intensity red colour
				returnString="\e[5;91m"
			else
				#use plain red colour
				returnString="\e[0;31m"
			fi
		else
			#use plain blue colour
			returnString="\e[0;36m"
		fi
	fi
fi

#add the battery value to the string
returnString=${returnString}${batValue}
#output the string (with substitution for colours)
echo -e $returnString
